global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
- job_name: app
  static_configs:
  - targets:
    - host.docker.internal:3010    
- job_name: springBoot3
  metrics_path: /actuator/prometheus
  static_configs:
  - targets:
    - host.docker.internal:1980